// engine/plugins/world_location_tracker/editor/state.js

export const SOCKET = window.socket || null;
export const HOST_CONTAINER = document.getElementById('pluginViewContainer');
export const DEFAULT_DRAW_HINT = 'Click to place area vertices. Double-click or use Finish Area to close the polygon. Right-click while drawing to remove the last point.';
export const AREA_COLORS = ['#4f8fc0', '#63b16d', '#d99d43', '#b66fd2', '#d26f7d', '#4ec0b8', '#db6d53', '#88a64a'];
export const NODE_TYPE_DEFAULTS = ['Capital', 'City', 'Port', 'POI', 'Ruin', 'Village'];
export const AREA_TYPE_DEFAULTS = ['continent', 'nation', 'region', 'city_region', 'district', 'subregion'];
export const DEFAULT_BIOME_MASK_FILE = 'biome_mask.png';
export const DEFAULT_BIOMES = [
    { id: 'forest', label: 'Forest', color: '#4fb84f', needs_boat: false, slows_down: false, is_road: false, is_river: false },
    { id: 'rainforest', label: 'Rainforest', color: '#126b35', needs_boat: false, slows_down: true, is_road: false, is_river: false },
    { id: 'plains', label: 'Plains', color: '#95c95c', needs_boat: false, slows_down: false, is_road: false, is_river: false },
    { id: 'mountains', label: 'Mountains', color: '#55585d', needs_boat: false, slows_down: true, is_road: false, is_river: false },
    { id: 'desert', label: 'Desert', color: '#d8bd74', needs_boat: false, slows_down: false, is_road: false, is_river: false },
    { id: 'snowfield', label: 'Snowfield', color: '#f2f5f6', needs_boat: false, slows_down: false, is_road: false, is_river: false },
    { id: 'sea', label: 'Sea', color: '#236db5', needs_boat: true, slows_down: false, is_road: false, is_river: false },
    { id: 'river', label: 'River', color: '#61bce8', needs_boat: false, slows_down: false, is_road: false, is_river: true },
    { id: 'road', label: 'Road', color: '#b8b8b8', needs_boat: false, slows_down: false, is_road: true, is_river: false },
    { id: 'town', label: 'Town', color: '#d0d0c8', needs_boat: false, slows_down: false, is_road: false, is_river: false }
];

export const state = {
    WORLD_PACKAGE_PATH: '',
    worldData: null,
    imageUrl: '',
    imageFile: '',
    isTiled: false,
    tileUrl: '',
    map: null,
    imageOverlay: null,
    originMarker: null,
    nodeMarkers: [],
    areaLayers: [],
    biomeOverlay: null,
    biomeCanvas: null,
    biomeCtx: null,
    biomeMaskUrl: '',
    selectedBiomeId: 'forest',
    biomeBrushSize: 24,
    biomeMaskOpacity: 0.45,
    biomeEraser: false,
    biomePainting: false,
    biomeRightPanning: false,
    biomeRightPanLastPoint: null,
    biomeBrushPreviewEl: null,
    biomeMaskLoaded: false,
    biomeOverlayUpdateQueued: false,
    draftAreaLayer: null,
    imageBounds: null,
    imageDimensions: { width: 0, height: 0 },
    mapScale: 1,
    maxNativeZoom: 0,
    selectedNodeId: null,
    selectedAreaId: null,
    interactionMode: 'pan',
    draftAreaPoints: [],
    draftAreaParentId: null,
    activeIndexTab: 'nodes',
    indexSearch: '',
    openTypeSuggestions: null,
    dirty: false,
    dirtyReasons: new Set(),
    saving: false,
    simOriginNodeUid: null,
    simDestinationNodeUid: null,
    simRequestSeq: 0,
    simPendingRequestId: null,
    simLatestRequestId: null
};

export const el = {
    root: document.getElementById('world-map-editor-root'),
    packageLabel: document.getElementById('world-map-package-label'),
    dirtyPill: document.getElementById('world-map-dirty-pill'),
    imageLabel: document.getElementById('world-map-image-label'),
    status: document.getElementById('world-map-status'),
    uploadBtn: document.getElementById('world-map-upload-btn'),
    saveBtn: document.getElementById('world-map-save-btn'),
    saveNudge: document.getElementById('world-map-save-nudge'),
    saveNudgeBtn: document.getElementById('world-map-save-nudge-btn'),
    imageInput: document.getElementById('world-map-image-input'),
    nodeTotal: document.getElementById('world-map-node-total'),
    areaTotal: document.getElementById('world-map-area-total'),
    biomeTotal: document.getElementById('world-map-biome-total'),
    addNodeBtn: document.getElementById('world-map-add-node-btn'),
    originModeBtn: document.getElementById('world-map-origin-mode-btn'),
    drawAreaBtn: document.getElementById('world-map-draw-area-btn'),
    finishAreaBtn: document.getElementById('world-map-finish-area-btn'),
    cancelAreaBtn: document.getElementById('world-map-cancel-area-btn'),
    resetViewBtn: document.getElementById('world-map-reset-view-btn'),
    modeIndicator: document.getElementById('world-map-mode-indicator'),
    drawHint: document.getElementById('world-map-draw-hint'),
    selectionSummary: document.getElementById('world-map-selection-summary'),
    cursor: document.getElementById('world-map-cursor'),
    originReadout: document.getElementById('world-map-origin-readout'),
    areaReadout: document.getElementById('world-map-area-readout'),
    canvasEmpty: document.getElementById('world-map-canvas-empty'),
    map: document.getElementById('world-map-leaflet'),
    nodeCount: document.getElementById('world-map-node-count'),
    nodeTabBtn: document.getElementById('world-map-tab-nodes'),
    areaTabBtn: document.getElementById('world-map-tab-areas'),
    biomeTabBtn: document.getElementById('world-map-tab-biomes'),
    indexSearch: document.getElementById('world-map-index-search'),
    nodeList: document.getElementById('world-map-node-list'),
    biomeList: document.getElementById('world-map-biome-list'),
    biomeEditorPanel: document.getElementById('world-map-biome-editor-panel'),
    biomeCount: document.getElementById('world-map-biome-count'),
    addBiomeBtn: document.getElementById('world-map-add-biome-btn'),
    deleteBiomeBtn: document.getElementById('world-map-delete-biome-btn'),
    clearBiomeMaskBtn: document.getElementById('world-map-clear-biome-mask-btn'),
    biomeName: document.getElementById('wm-biome-name'),
    biomeColor: document.getElementById('wm-biome-color'),
    biomeNeedsBoat: document.getElementById('wm-biome-needs-boat'),
    biomeSlowsDown: document.getElementById('wm-biome-slows-down'),
    biomeIsRoad: document.getElementById('wm-biome-is-road'),
    biomeIsRiver: document.getElementById('wm-biome-is-river'),
    biomeBrushSize: document.getElementById('wm-biome-brush-size'),
    biomeBrushSizeReadout: document.getElementById('wm-biome-brush-size-readout'),
    biomeOpacity: document.getElementById('wm-biome-opacity'),
    biomeOpacityReadout: document.getElementById('wm-biome-opacity-readout'),
    biomeEraser: document.getElementById('wm-biome-eraser'),
    nodeEditorPanel: document.getElementById('world-map-node-editor-panel'),
    nodeTitle: document.getElementById('world-map-node-title'),
    nodeAreaReadout: document.getElementById('world-map-node-area-readout'),
    deleteNodeBtn: document.getElementById('world-map-delete-node-btn'),
    areaCount: document.getElementById('world-map-area-count'),
    areaList: document.getElementById('world-map-area-list'),
    areaEditorPanel: document.getElementById('world-map-area-editor-panel'),
    areaTitle: document.getElementById('world-map-area-title'),
    areaHierarchy: document.getElementById('world-map-area-hierarchy'),
    areaPoints: document.getElementById('world-map-area-points'),
    deleteAreaBtn: document.getElementById('world-map-delete-area-btn'),
    originX: document.getElementById('wm-origin-x'),
    originY: document.getElementById('wm-origin-y'),
    scaleFactor: document.getElementById('wm-scale-factor'),
    pixelsPerKm: document.getElementById('wm-pixels-per-km'),
    walkSpeed: document.getElementById('wm-walk-speed'),
    windingFactor: document.getElementById('wm-winding-factor'),
    simState: document.getElementById('world-map-travel-sim-state'),
    simMessage: document.getElementById('world-map-travel-sim-message'),
    simOriginNode: document.getElementById('wm-sim-origin-node'),
    simDestinationNode: document.getElementById('wm-sim-destination-node'),
    simDistance: document.getElementById('world-map-travel-sim-distance'),
    simDays: document.getElementById('world-map-travel-sim-days'),
    simNarrativeLabel: document.getElementById('world-map-travel-sim-label'),
    nodeName: document.getElementById('wm-node-name'),
    nodeType: document.getElementById('wm-node-type'),
    nodeTypeSuggestions: document.getElementById('world-map-node-type-suggestions'),
    nodeWorldX: document.getElementById('wm-node-world-x'),
    nodeWorldY: document.getElementById('wm-node-world-y'),
    nodeDescription: document.getElementById('wm-node-description'),
    nodeTags: document.getElementById('wm-node-tags'),
    areaName: document.getElementById('wm-area-name'),
    areaKind: document.getElementById('wm-area-kind'),
    areaTypeSuggestions: document.getElementById('world-map-area-type-suggestions'),
    areaParent: document.getElementById('wm-area-parent'),
    areaColor: document.getElementById('wm-area-color'),
    areaTags: document.getElementById('wm-area-tags'),
    areaDescription: document.getElementById('wm-area-description')
};

export function refreshDomRefs() {
    Object.assign(el, {
        root: document.getElementById('world-map-editor-root'),
        packageLabel: document.getElementById('world-map-package-label'),
        dirtyPill: document.getElementById('world-map-dirty-pill'),
        imageLabel: document.getElementById('world-map-image-label'),
        status: document.getElementById('world-map-status'),
        uploadBtn: document.getElementById('world-map-upload-btn'),
        saveBtn: document.getElementById('world-map-save-btn'),
        saveNudge: document.getElementById('world-map-save-nudge'),
        saveNudgeBtn: document.getElementById('world-map-save-nudge-btn'),
        imageInput: document.getElementById('world-map-image-input'),
        nodeTotal: document.getElementById('world-map-node-total'),
        areaTotal: document.getElementById('world-map-area-total'),
        biomeTotal: document.getElementById('world-map-biome-total'),
        addNodeBtn: document.getElementById('world-map-add-node-btn'),
        originModeBtn: document.getElementById('world-map-origin-mode-btn'),
        drawAreaBtn: document.getElementById('world-map-draw-area-btn'),
        finishAreaBtn: document.getElementById('world-map-finish-area-btn'),
        cancelAreaBtn: document.getElementById('world-map-cancel-area-btn'),
        resetViewBtn: document.getElementById('world-map-reset-view-btn'),
        modeIndicator: document.getElementById('world-map-mode-indicator'),
        drawHint: document.getElementById('world-map-draw-hint'),
        selectionSummary: document.getElementById('world-map-selection-summary'),
        cursor: document.getElementById('world-map-cursor'),
        originReadout: document.getElementById('world-map-origin-readout'),
        areaReadout: document.getElementById('world-map-area-readout'),
        canvasEmpty: document.getElementById('world-map-canvas-empty'),
        map: document.getElementById('world-map-leaflet'),
        nodeCount: document.getElementById('world-map-node-count'),
        nodeTabBtn: document.getElementById('world-map-tab-nodes'),
        areaTabBtn: document.getElementById('world-map-tab-areas'),
        biomeTabBtn: document.getElementById('world-map-tab-biomes'),
        indexSearch: document.getElementById('world-map-index-search'),
        nodeList: document.getElementById('world-map-node-list'),
        biomeList: document.getElementById('world-map-biome-list'),
        biomeEditorPanel: document.getElementById('world-map-biome-editor-panel'),
        biomeCount: document.getElementById('world-map-biome-count'),
        addBiomeBtn: document.getElementById('world-map-add-biome-btn'),
        deleteBiomeBtn: document.getElementById('world-map-delete-biome-btn'),
        clearBiomeMaskBtn: document.getElementById('world-map-clear-biome-mask-btn'),
        biomeName: document.getElementById('wm-biome-name'),
        biomeColor: document.getElementById('wm-biome-color'),
        biomeNeedsBoat: document.getElementById('wm-biome-needs-boat'),
        biomeSlowsDown: document.getElementById('wm-biome-slows-down'),
        biomeIsRoad: document.getElementById('wm-biome-is-road'),
        biomeIsRiver: document.getElementById('wm-biome-is-river'),
        biomeBrushSize: document.getElementById('wm-biome-brush-size'),
        biomeBrushSizeReadout: document.getElementById('wm-biome-brush-size-readout'),
        biomeOpacity: document.getElementById('wm-biome-opacity'),
        biomeOpacityReadout: document.getElementById('wm-biome-opacity-readout'),
        biomeEraser: document.getElementById('wm-biome-eraser'),
        nodeEditorPanel: document.getElementById('world-map-node-editor-panel'),
        nodeTitle: document.getElementById('world-map-node-title'),
        nodeAreaReadout: document.getElementById('world-map-node-area-readout'),
        deleteNodeBtn: document.getElementById('world-map-delete-node-btn'),
        areaCount: document.getElementById('world-map-area-count'),
        areaList: document.getElementById('world-map-area-list'),
        areaEditorPanel: document.getElementById('world-map-area-editor-panel'),
        areaTitle: document.getElementById('world-map-area-title'),
        areaHierarchy: document.getElementById('world-map-area-hierarchy'),
        areaPoints: document.getElementById('world-map-area-points'),
        deleteAreaBtn: document.getElementById('world-map-delete-area-btn'),
        originX: document.getElementById('wm-origin-x'),
        originY: document.getElementById('wm-origin-y'),
        scaleFactor: document.getElementById('wm-scale-factor'),
        pixelsPerKm: document.getElementById('wm-pixels-per-km'),
        walkSpeed: document.getElementById('wm-walk-speed'),
        windingFactor: document.getElementById('wm-winding-factor'),
        simState: document.getElementById('world-map-travel-sim-state'),
        simMessage: document.getElementById('world-map-travel-sim-message'),
        simOriginNode: document.getElementById('wm-sim-origin-node'),
        simDestinationNode: document.getElementById('wm-sim-destination-node'),
        simDistance: document.getElementById('world-map-travel-sim-distance'),
        simDays: document.getElementById('world-map-travel-sim-days'),
        simNarrativeLabel: document.getElementById('world-map-travel-sim-label'),
        nodeName: document.getElementById('wm-node-name'),
        nodeType: document.getElementById('wm-node-type'),
        nodeTypeSuggestions: document.getElementById('world-map-node-type-suggestions'),
        nodeWorldX: document.getElementById('wm-node-world-x'),
        nodeWorldY: document.getElementById('wm-node-world-y'),
        nodeDescription: document.getElementById('wm-node-description'),
        nodeTags: document.getElementById('wm-node-tags'),
        areaName: document.getElementById('wm-area-name'),
        areaKind: document.getElementById('wm-area-kind'),
        areaTypeSuggestions: document.getElementById('world-map-area-type-suggestions'),
        areaParent: document.getElementById('wm-area-parent'),
        areaColor: document.getElementById('wm-area-color'),
        areaTags: document.getElementById('wm-area-tags'),
        areaDescription: document.getElementById('wm-area-description')
    });
}

export const cleanupFns = [];
